- name: Ensure last_imports directory exists
  ansible.builtin.file:
    path: /ecorp/data/controller/last_imports/git_import
    state: directory
    mode: '0755'

- name: Init git import enviroment
  shell: |
    git config --global credential.helper store
    git credential approve << EOF
    protocol=http
    host=gitlab.{{ ECORP_DNS_CORE_ZONE_NAME }}
    username=root
    password={{ lookup('env', 'GITLAB_ROOT_PASSWORD') }}
    EOF

    git config --global --add safe.directory /ecorp

- name: "Include git repos definitions"
  include_vars:
    file: /ecorp/settings/git-repos.yml

- name: "Add/Update users"
  loop: "{{ repos }}"
  loop_control:
    loop_var: repo
  include_tasks: import_repo.yml
