
x-def: &def
  restart: unless-stopped
  networks:
    core:
  dns:
    # Yes, we use DC as DNS of course
    - ${NET_DC}

services:
  dns:
    image: coredns/coredns
    restart: unless-stopped
    entrypoint: /coredns -conf /dns/Corefile
    volumes:
      # zone configurations
      - ./data/dns/:/dns/
    networks:
      core:
        ipv4_address: ${NET_DNS}

  dc:
    <<: *def
    privileged: true # required to manage file ACLs
    hostname: dc.${DC_DOMAIN}
    build:
      context: units/dc
    environment:
      - DC_DNS_FORWARDER=${NET_DNS}
      - DC_REALM
      - DC_DOMAIN
      - DC_ADMIN_PASS
    # can't bind mount with acl support, so I use a volume
    volumes:
      - dc:/var/lib/samba/
    networks:
      core:
        ipv4_address: ${NET_DC}

  controller:
    <<: *def
    build:
      context: units/controller
    environment:
      - ECORP_DNS_CORE_ZONE_NAME
      - DC_REALM
      - DC_DOMAIN
      - DC_ADMIN_PASS
    volumes:
      - ./:/ecorp
      - ./data/controller/root:/root
      - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    <<: *def
    image: 'gitlab/gitlab-ce:latest'
    environment:
      - GITLAB_ROOT_PASSWORD
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab

  core-gitlab-runner:
    <<: *def
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/gitlab-runner/conf:/etc/gitlab-runner

volumes:
  # I dont like this, but ACLs does not works with bind
  dc:

networks:
  core:
    ipam:
      driver: default
      config:
        - subnet: ${NET_CIDR} 