#!/bin/bash

# helper script
# Used to wrap custom operations inside one script
############################# RH helper functions ##############################

ROOT=$(dirname $(readlink -f $0))

_rh_try_ret_help()
{
	if [ ! -z $RH_RUNTIME_REQUEST_HELP ]
	then
		echo $1
		exit 1;
	fi
}

spawn_default()
{
	cd ${ROOT}
	cd $2
	if ! [ -e $3 ]
	then
		if [ $1 = 'plain' ]
		then
			cp $3'.default' $3
		elif [ $1 = 'eval' ]
		then
			bash <(echo 'cat << EOF' ; cat $3'.default' ; echo 'EOF') > $3
		fi
	fi
	cd ${ROOT}
}

prepare()
{
	_rh_try_ret_help 'Do the necessary preparation steps before launching: spawning default config files, creating directories'
    
	cd ${ROOT}

    mkdir -p data/dns/zones/ data/storage

	spawn_default eval . .env
	spawn_default plain settings ad-users.yml
	spawn_default plain settings steps.yml
}

dc()
{
	docker compose -p ecorp "$@"
}

up()
{
    _rh_try_ret_help 'Starts the infrastructure and follows until ready'
    set -e
    
    cd ${ROOT}

	prepare
    dc up -d --build
	follow_provision
}

follow_provision()
{
	_rh_try_ret_help 'Follow current provisioning process output running in container until the end'
	dc exec controller /ecorp/units/controller/code/ecorp follow_provision
}

provision()
{
	_rh_try_ret_help 'Run provision in controller'
	dc exec controller /ecorp/units/controller/code/ecorp controller_ansible_provision
}

run_in_container()
{
	_rh_try_ret_help 'Launch the ecorp infrastructure in a container'
	# TODO only raw git clone
	cd ${ROOT}
	cd dev/wrap_container
	dc up -d
	cat << EOF | dc exec -T ecorp bash
	set -ex
		# wait for docker ready
		rem=30
		while ! docker ps && [ \$rem '>' 0 ]
		do
			rem=\$(expr \$rem - 1)
			sleep 1
			echo "Waiting secounds remaining: "\$rem
		done
	docker ps
	# disable raw protection prevents accessing containers routed style
	# iptables -t raw -I PREROUTING 1 -j ACCEPT

git config --global --add safe.directory /source/.git
git clone /source ecorp
cd ecorp
./ecorp up

	echo ""
	echo "To make this internal network segment available on host machine, add this route:"
	echo "route add -net \$(source ./.env; echo \$NET_CIDR) gw \$(hostname -i)"
EOF

# cycle in container:
# docker compose down -v ; git clean -fxd ; git pull origin master ; ./ecorp up ; docker logs -f ecorp-controller-1

}

ci_test_infra()
{
	_rh_try_ret_help 'CI/CD: Launch the ecorp infrastructure in a container for testing.'
	
	cd ${ROOT}
	cd dev/ci_test
	docker compose -p ci_test up -d --build

	trap 'docker compose -p ci_test down -v' EXIT

	cat << EOF | docker compose -p ci_test exec -T ecorp bash
	set -ex
	# wait for docker ready
	rem=30
	while ! docker ps && [ \$rem '>' 0 ]
	do
		rem=\$(expr \$rem - 1)
		sleep 1
		echo "Waiting secounds remaining: "\$rem
	done
	docker ps

	cd /source
	./ecorp up
EOF
}

purge()
{
	_rh_try_ret_help 'Purge the system: stops all container and remove all user files and making git working directory clean as a whistle'
	cd ${ROOT}
	dc down -v
	# git clean -fxd
	# because of git folders (recognised as sub repositories and excluded from clean)
	rm -Rf ./data/*
}

############################ RH built-in functions #############################

help()
{
	_rh_try_ret_help "Returns RH help with the list of all annotated functions"

	echo "RH stands for 'right hand'. It is a wrapper script wherein you can collect tiny commands."
	echo "Specify one righthand function from the followings:"

	RH_RUNTIME_REQUEST_HELP=true

	for f in ${RH_FUNCTIONS[@]}
	do
		# if the command has help
		if type $f | grep -qzP '{\s+_rh_try_ret_help '
		then
			echo -e "\t$f - "$($f)
		fi
	done
}

############################## Application area ################################

# Collection available commands
RH_FUNCTIONS=()

for func in `typeset -F | grep -Po '(?<=-f).*$' | sort`
do
	RH_FUNCTIONS+=($func);
done

# print help if nothing specified

if [ $# '<' '1' ]
then
	help
	exit 1
fi

# run command
for f in ${RH_FUNCTIONS[@]}
do
	if [ "$1" "=" "$f" ]
	then
		$f "${@:2}"
		exit $?
	fi
done

echo "Righthand function $1 not found, so now printing help..."
help
exit 1