#!/bin/bash

# helper script
# Used to wrap custom operations inside one script
############################# RH helper functions ##############################

ROOT=$(dirname $(readlink -f $0))

_rh_try_ret_help()
{
	if [ ! -z $RH_RUNTIME_REQUEST_HELP ]
	then
		echo $1
		exit 1;
	fi
}

up()
{
    _rh_try_ret_help 'Starts the infrastructure'
    set -e
    
    cd ${ROOT}

    mkdir -p data/dns/zones/

    docker compose up -d --build
}

go_dind()
{
    _rh_try_ret_help ''

}


controller()
{
    _rh_try_ret_help 'Enters the shell of the controller node (if the infrastructure is running)'
    docker compose exec -it controller bash
}


##### In container functions #####

entrypoint()
{
    _rh_try_ret_help 'Run entrypoint logic inside controller container'
    service cron start
    service apache2 start

    service xrdp start

    service_docker_dns_zones &

    exec /bin/tail -f /dev/null
}

regenerate_dns_zone_docker()
{
	# create docker dir if not exists
	mkdir -p /ecorp/data/dns/zones/dynamic/docker/
	# delete all old dynamic files in dir
	rm -rf /ecorp/data/dns/zones/dynamic/docker/* || true

	{
		cat << EOF 
\$ORIGIN ${DNS_CORE_ZONE_NAME}.
\$TTL 3600
@   IN  SOA ns1.${DNS_CORE_ZONE_NAME}. admin.${DNS_CORE_ZONE_NAME}. (
        $RANDOM ; serial
        3600       ; refresh
        1800       ; retry
        1209600    ; expire
        3600 )     ; minimum

EOF

	docker ps -q | xargs -n 1 docker inspect --format '{{ if .Config.Labels.dns_names }}{{ .Config.Labels.dns_names }}{{end}} {{range .NetworkSettings.Networks}}{{ range .DNSNames}} {{.}} {{end}}{{end}} {{range .NetworkSettings.Networks}} {{.IPAddress}}{{end}}' \
	| while read -r -a REC
	do
		pn=${#REC[@]}
		if [ $pn '>' 1 ]
		then
			lst=$(expr $pn - 1)
			for e in ${REC[@]:0:$lst}
			do
				echo $e IN A ${REC[$lst]}
			done
			echo 
		fi
	done

	} > /ecorp/data/dns/zones/dynamic/docker/${DNS_CORE_ZONE_NAME}
}

service_docker_dns_zones()
{
    regenerate_dns_zone_docker
    docker events --filter 'event=start' --filter 'event=restart' --filter 'event=die' | while IFS= read -r line
    do
        # Start or die event
        if grep -qP '^[^ ]+ container (start|die)' <<< $line
        then
                regenerate_dns_zone_docker
        fi
    done
}

############################ RH built-in functions #############################

help()
{
	_rh_try_ret_help "Returns RH help with the list of all annotated functions"

	echo "RH stands for 'right hand'. It is a wrapper script wherein you can collect tiny commands."
	echo "Specify one righthand function from the followings:"

	RH_RUNTIME_REQUEST_HELP=true

	for f in ${RH_FUNCTIONS[@]}
	do
		# if the command has help
		if type $f | grep -qzP '{\s+_rh_try_ret_help '
		then
			echo -e "\t$f - "$($f)
		fi
	done
}

############################## Application area ################################

# Collection available commands
RH_FUNCTIONS=()

for func in `typeset -F | grep -Po '(?<=-f).*$' | sort`
do
	RH_FUNCTIONS+=($func);
done

# print help if nothing specified

if [ $# '<' '1' ]
then
	help
	exit 1
fi

# run command
for f in ${RH_FUNCTIONS[@]}
do
	if [ "$1" "=" "$f" ]
	then
		$f "${@:2}"
		exit $?
	fi
done

echo "Righthand function $1 not found, so now printing help..."
help
exit 1