---
- name: Install community.general collection
  ansible.galaxy.collection:
    name: community.general
    type: collection
    state: present

- name: Configure Mattermost LDAP connection
  community.general.json_patch:
    src: "/opt/mattermost/config/config.json"
    content:
      - op: replace
        path: "/LdapSettings/Enable"
        value: true
      - op: replace
        path: "/LdapSettings/LdapServer"
        value: 'dc.{{ DNS_CORE_ZONE_NAME }}'
      - op: replace
        path: "/LdapSettings/LdapPort"
        value: "636"
      - op: replace
        path: "/LdapSettings/BindDN"
        value: 'Administrator@{{ lookup("env", "DC_DOMAIN") }}'
      - op: replace
        path: "/LdapSettings/BindPassword"
        value: '{{ lookup("env", "DC_ADMIN_PASS") }}'
      - op: replace
        path: "/LdapSettings/BaseDN"
        value: 'DC={{ lookup("env", "DC_REALM") }}'
      - op: replace
        path: "/LdapSettings/UserFilter"
        value: "(objectClass=user)"
      - op: replace
        path: "/LdapSettings/FirstNameAttribute"
        value: "givenName"
      - op: replace
        path: "/LdapSettings/LastNameAttribute"
        value: "sn"
      - op: replace
        path: "/LdapSettings/EmailAttribute"
        value: "mail"
      - op: replace
        path: "/LdapSettings/UsernameAttribute"
        value: "sAMAccountName"
      - op: replace
        path: "/LdapSettings/LoginFieldName"
        value: "sAMAccountName"
      - op: replace
        path: "/LdapSettings/IdAttribute"
        value: "uid" # Common for OpenLDAP
      - op: replace
        path: "/LdapSettings/SyncIntervalMinutes"
        value: "10"
      - op: replace
        path: "/LdapSettings/EnableSync"
        value: true
      - op: replace
        path: "/LdapSettings/SkipTLSVerify"
        value: true
      - op: replace
        path: "/LdapSettings/TLSStartTLS"
        value: false
      - op: replace
        path: "/LdapSettings/TLSStrict"
        value: false # Set to true for strict TLS
    create: false # Mattermost config.json should already exist
  register: mm_config
  notify: Restart Mattermost

- name: Restart Mattermost
  command: docker restart ecorp-mattermost-1
  when: mm_config.changed