all:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    ECORP_DNS_CORE_ZONE_NAME: "{{ lookup('env', 'ECORP_DNS_CORE_ZONE_NAME') }}"

    ad_exec: "docker exec -t ecorp-dc-1"
    gitlab_url: "http://gitlab.{{ ECORP_DNS_CORE_ZONE_NAME }}"

    runner_default_target: "docker exec ecorp-core-gitlab-runner-1"

    runners:
      - name: "Core infra runner"
        tags: core
        type: docker
        run_untagged: false
        opts: " --docker-dns '{{ lookup('env', 'NET_DC') }}' --docker-pull-policy 'if-not-present' --docker-volumes /var/run/docker.sock:/var/run/docker.sock "
        target: "docker exec ecorp-core-gitlab-runner-1"
      
      - name: "Core infra shared runner"
        type: docker
        run_untagged: true
        opts: " --docker-dns '{{ lookup('env', 'NET_DC') }}' --docker-pull-policy 'if-not-present' --docker-volumes docker:/var/lib/docker "
        target: "docker exec ecorp-core-gitlab-runner-1"
