all:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    ECORP_DNS_CORE_ZONE_NAME: "{{ lookup('env', 'ECORP_DNS_CORE_ZONE_NAME') }}"

    ad_exec: "docker exec -t ecorp-dc-1"
    gitlab_url: "http://gitlab.{{ ECORP_DNS_CORE_ZONE_NAME }}"

    runner_default_target: "docker exec ecorp-core-gitlab-runner-1"

    runners:
      - name: "Core infra runner"
        tags: core
        type: docker
        run_untagged: false
        opts: ""
        target: "docker exec ecorp-core-gitlab-runner-1"