- name: Import roles and users into DC
  hosts: all
  roles:
    - gitlab/configure
    - dc/import_roles_users
    - gitlab/dc_connect
    #- mattermost/dc_connect
    - gitlab/runner_register
    #- util/git_import
