services:
  ecorp:
    # For image: `./ecorp build_diorama_image` before launch this compose
    image: ecorp_diorama:latest
    restart: unless-stopped
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - systempaths=unconfined
    tmpfs:
      - /tmp
      - /run
    volumes:
      # Required for systemd
      - /sys/fs/cgroup:/sys/fs/cgroup
      # Required for docker (Overlay can't be mounted on overlay)
      - docker:/var/lib/docker
      - containerd:/var/lib/containerd
      - storage:/ecorp/data/storage

volumes:
  docker:
  containerd:
  storage: