---
- name: Read repositories configuration
  ansible.builtin.include_vars:
    file: /ecorp/settings/repos.yml
    name: repos_config

- name: Ensure local directory for repositories exists
  ansible.builtin.file:
    path: "/ecorp/data/git_repos"
    state: directory
    mode: '0755'

- name: Process main repositories
  ansible.builtin.include_tasks: process_repo.yml
  loop: "{{ repos_config.repos }}"
  loop_control:
    loop_var: current_repo
    label: "{{ current_repo.url }}"

- name: Process extra repositories
  ansible.builtin.include_tasks: process_extra_repo.yml
  loop: "{{ repos_config.repos | selectattr('extra_repo', 'defined') | map(attribute='extra_repo') | flatten }}"
  loop_control:
    loop_var: extra_repo_url
    label: "{{ extra_repo_url }}"