- name: Check if GitLab Runner is already registered
  ansible.builtin.shell: |
    {{ runner.target | default(runner_default_target) }} gitlab-runner list 2>&1 | grep -F "{{ runner.name }}"
  register: runner_registered_result
  ignore_errors: true
  changed_when: false

- name: Set runner registered state
  ansible.builtin.set_fact:
    runners_registered: "{{ runners_registered | combine({(runner.name): runner_registered_result.rc == 0}) }}"
