- name: Set runners_registered default value
  ansible.builtin.set_fact:
    runners_registered: {}

- name: Check runner registered
  include_tasks: check_runner_registered.yml
  loop: "{{ runners }}"
  loop_control:
    loop_var: runner
