- name: Check all runner registered
  ansible.builtin.include_tasks: is_runners_registered.yml

- name: Register GitLab Runner
  ansible.builtin.include_tasks: register_runner.yml
  loop: "{{ runners }}"
  loop_control:
    loop_var: runner
  when: not runners_registered[runner.name]
