- name: Register GitLab Runner
  ansible.builtin.shell: |
    {{ runner.target | default(runner_default_target) }} gitlab-runner register \
      --non-interactive \
      --url "http://gitlab.{{ DNS_CORE_ZONE_NAME }}" \
      --registration-token "{{ gitlab_runner_registration_token }}" \
      --executor "{{ runner.type | default('docker') }}" \
      --description "{{ runner.name }}" \
      --tag-list "{{ runner.tags | default('') }}" \
      --docker-image "alpine:latest" \
      --run-untagged="{{ runner.run_untagged | default('false') }}" \
      --locked="false" \
      --access-level="not_protected" \
      {{ runner.opts | default('') }}
  delegate_to: localhost