#!/bin/bash

cfg_smb_conf()
{
cat << EOF
[global]
    dns forwarder = $DC_DNS_FORWARDER
    netbios name = DC1
    realm = $DC_REALM
    server role = active directory domain controller
    workgroup = $DC_DOMAIN
    idmap_ldb:use rfc2307 = yes
    tls enabled  = yes

[sysvol]
    path = /var/lib/samba/sysvol
    read only = No

[netlogon]
    path = /var/lib/samba/sysvol/$DC_REALM/scripts
    read only = No

EOF
}

cfg_krb5_conf()
{
cat << EOF
[libdefaults]
  default_realm = $DC_REALM
  dns_lookup_realm = false
  dns_lookup_kdc = true

[realms]
$DC_REALM = {
  default_domain = $DC_DOMAIN
}

[domain_realm]
  dc.$DC_REALM = $DC_REALM
EOF
}

render_file()
{
    {
        echo "cat << EOF"
        cat $1
        echo "EOF"
    } | bash
}

entrypoint()
{
    set -ex
    mkdir -p /var/lib/samba/{usershare,private,printers,winbindd_privileged}
    mkdir -p /var/lib/samba/sysvol/$DC_REALM/scripts

    # render config
    cfg_smb_conf | tee /etc/samba/smb.conf

    # kerberos config
    #cfg_krb5_conf > /etc/krb5.conf.d/samba-dc   
    if [ ! -e /var/lib/samba/domain_provisioned ]
    then
      samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL \
        --realm=$DC_REALM --domain=$DC_DOMAIN --adminpass=$DC_ADMIN_PASS

      touch /var/lib/samba/domain_provisioned
    fi
    # start service
    service samba-ad-dc start

    tail -f /dev/null
}

"$@"