#!/bin/bash

# helper script
# Used to wrap custom operations inside one script
############################# RH helper functions ##############################

ROOT=$(dirname $(readlink -f $0))

_rh_try_ret_help()
{
	if [ ! -z $RH_RUNTIME_REQUEST_HELP ]
	then
		echo $1
		exit 1;
	fi
}

PROV_LOG_DIR=/ecorp/data/controller/provision/logs/

##### In container functions #####

entrypoint()
{
    _rh_try_ret_help 'Run entrypoint logic inside controller container'

	# Make docker available for www-data.
	chown root:www-data /var/run/docker.sock
	chmod 660 /var/run/docker.sock
	usermod -aG sudo www-data

	echo '%sudo         ALL = (ALL) NOPASSWD: ALL' >  /etc/sudoers.d/sudoers-nopwd
	chmod 440 /etc/sudoers.d/sudoers-nopwd

	# Place right at the start, in first start dns container is dying because of missing
	# Corefile configuration, so generate as fast as possible.
	service_docker_dns_zones &

	if [ ! -z $HOME_WWW_USER ] && [ ! -z $HOME_WWW_PASSWORD ]
	then
		rm /tmp/htpasswd || true
		htpasswd -bc /tmp/htpasswd $HOME_WWW_USER $HOME_WWW_PASSWORD
	fi

	www_conf > /etc/apache2/sites-enabled/000-default.conf
	a2enmod cgi
    service apache2 start

	service cron start

    # make login possible without CAP_AUDIT_WRITE: https://stackoverflow.com/questions/21391142/why-is-it-needed-to-set-pam-loginuid-to-its-optional-value-with-docker
	sed -i '/session    required     pam_loginuid.so/c\session    optional   pam_loginuid.so' /etc/pam.d/sshd
	
	gen_ssh_master_key

	service ssh start

	mkdir -p $PROV_LOG_DIR
	controller_ansible_provision

    exec /bin/tail -f /dev/null
}

gen_ssh_master_key()
{
	if [ -e /ecorp/data/controller/ssh/id_rsa ]
	then
		mkdir -p /ecorp/data/controller/ssh/
		ssh-keygen -q -t rsa -N '' -f /ecorp/data/controller/ssh/id_rsa <<< y
	fi
}

controller_ansible_provision()
{
	cd /ecorp/units/controller/code/ansible

	if ! chk_prov
	then
		echo "Provision already running"
		exit 1
	fi

	log=${PROV_LOG_DIR}$(date +'%Y-%m-%d_%H-%M-%S')
	ansible-playbook -i hosts.yml provision.yml "$@" | tee -a $log
	ex=${PIPESTATUS[0]}
	echo $ex > ${log}".exit"
}

chk_prov()
{
	[ 0 = $(ps aux | grep ansible-playbook | grep -v grep | wc -l) ]
}

follow_provision()
{
	_rh_try_ret_help 'Follows running provision'

	if chk_prov
	then
		echo "Provisioning might not started yet, waiting a little bit"
		rem=30
		while chk_prov && [ $rem '>' 0 ]
		do
			rem=$(expr $rem - 1)
			sleep 1
			echo "Waiting secounds remaining: "$rem
		done
	fi

	if chk_prov
	then
		echo "No provision running. exiting"
		exit 0
	fi


	last_file=$(ls -t ${PROV_LOG_DIR} | head -1)
	
	tail -n 9999999 -f ${PROV_LOG_DIR}${last_file} &
	TPID=$?

	exit_file=${PROV_LOG_DIR}${last_file}".exit"
	
	while ! [ -e $exit_file ]
	do
		sleep 1
	done
	ex=$(cat $exit_file)
	echo "Provisioning exited: "$ex
	kill $TPID
	exit $ex
}

regenerate_dns_zone_docker()
{
	source /ecorp/.env

	# create docker dir if not exists
	mkdir -p /ecorp/data/dns/zones/dynamic/docker/
	# delete all old dynamic files in dir
	rm -rf /ecorp/data/dns/zones/dynamic/docker/* || true

	{
		cat << EOF 
\$ORIGIN ${DNS_CORE_ZONE_NAME}.
\$TTL 3600
@   IN  SOA ns1.${DNS_CORE_ZONE_NAME}. admin.${DNS_CORE_ZONE_NAME}. (
        $RANDOM ; serial
        3600       ; refresh
        1800       ; retry
        1209600    ; expire
        3600 )     ; minimum

EOF

	DOCKER_DATA=$(docker ps -q | xargs -n 1 docker inspect --format '{{index .Config.Labels "dns_mode" }} {{ if .Config.Labels.dns_names }}{{ .Config.Labels.dns_names }}{{end}} {{range .NetworkSettings.Networks}}{{ range .DNSNames}} {{.}} {{end}}{{end}} {{range .NetworkSettings.Networks}} {{.IPAddress}}{{end}}')

	while read -r -a REC
	do
		pn=${#REC[@]}
		if [ $pn '>' 1 ]
		then
			lst=$(expr $pn - 1)
			lstp=$(expr $pn - 2)
			for e in ${REC[@]:1:$lstp}
			do
				if [ "delegated" = "${REC[0]}" ]
				then
					# only records witouth dot
					if ! [[ "${e}" =~ \. ]]
					then
						echo ${e}.ecorp-original-ip IN A ${REC[$lst]}
					fi
				else
					echo $e IN A ${REC[$lst]}
				fi
			done
			echo 
		fi
	done <<< "$DOCKER_DATA"

	} > /ecorp/data/dns/zones/dynamic/docker/${DNS_CORE_ZONE_NAME}

	{
	while read -r -a REC
	do
		pn=${#REC[@]}
		if [ $pn '>' 1 ]
		then
			if [ "delegated" = "${REC[0]}" ]
			then
				NAMES=()
			
				lst=$(expr $pn - 1)
				lstp=$(expr $pn - 2)
				for e in ${REC[@]:1:$lstp}
				do
					
				# only records witouth dot and not starting with number
				if ! [[ "${e}" =~ \. ]] && ! grep -qP '^\d' <<< "${e}"
				then
				ESC_RECORD=$(sed 's/\./\\./g' <<< "${e}.${DNS_CORE_ZONE_NAME}")
cat << EOF
${e}.${DNS_CORE_ZONE_NAME} {
	template ANY ANY ${e}.${DNS_CORE_ZONE_NAME} {
		match ^${ESC_RECORD}\.$
		answer "{{ .Name }} 60 IN CNAME ${e}.ecorp-original-ip.${DNS_CORE_ZONE_NAME}."
		fallthrough
	}
	forward . ${REC[$lst]}
}
EOF
				fi
				done
			fi
		fi
	done <<< "$DOCKER_DATA"


cat << EOF
. {
    # Serve authoritative zone from a BIND file
    auto . {
        directory /dns/zones/ (.*) {1}
        reload 3s 1s
    }

    # Include external forwarding rules
    forward . /etc/resolv.conf

    # Basic logging and health checks
    #log
    errors
    #prometheus :9153
    ready
    reload 3s 1s
}
EOF
	} > /ecorp/data/dns/Corefile

}


service_docker_dns_zones()
{
    regenerate_dns_zone_docker
    docker events --filter 'event=start' --filter 'event=restart' --filter 'event=die' | while IFS= read -r line
    do
        # Start or die event
        if grep -qP '^[^ ]+ container (start|die)' <<< $line
        then
            regenerate_dns_zone_docker
        fi
    done
}

www_conf()
{
	cat << EOF
	<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /ecorp/units/controller/code/www/
	ErrorLog \${APACHE_LOG_DIR}/error.log
	CustomLog \${APACHE_LOG_DIR}/access.log combined
	
	<Directory /ecorp/units/controller/code/www/>
		Options Indexes FollowSymLinks ExecCGI
		DirectoryIndex index.cgi index.html
		AddHandler cgi-script .cgi
		AllowOverride All
		SetEnv no-gzip 1
		SetEnv NS_SYNC_FLUSH 1
EOF

		if [ ! -z $HOME_WWW_USER ] && [ ! -z $HOME_WWW_PASSWORD ]
		then
		cat << EOF
			AuthType Basic
			AuthName "Restricted Area"
			AuthUserFile /tmp/htpasswd
			Require valid-user	
EOF
		else
			echo "		Require all granted"
		fi

	echo "</Directory>"
echo "</VirtualHost>"
}

dc_list_users()
{
	_rh_try_ret_help 'List users in Domain Controller inside controller container'
	source /ecorp/.env
	
	export LDAP_SERVER=$NET_DC
	export LDAP_PORT=636
	export LDAP_SSL=true

	export LDAP_BIND_DN="Administrator@${DC_DOMAIN}" # Example: 'cn=admin,dc=yourdomain,dc=com'
	export LDAP_BIND_PASSWORD=$DC_ADMIN_PASS
	
	export LDAP_SEARCH_BASE="dc=$DC_REALM" # Example: 'dc=yourdomain,dc=com'

	exec /ecorp/dev/ldap_list_users.py
}


############################ RH built-in functions #############################

help()
{
	_rh_try_ret_help "Returns RH help with the list of all annotated functions"

	echo "RH stands for 'right hand'. It is a wrapper script wherein you can collect tiny commands."
	echo "Specify one righthand function from the followings:"

	RH_RUNTIME_REQUEST_HELP=true

	for f in ${RH_FUNCTIONS[@]}
	do
		# if the command has help
		if type $f | grep -qzP '{\s+_rh_try_ret_help '
		then
			echo -e "\t$f - "$($f)
		fi
	done
}



############################## Application area ################################

# Collection available commands
RH_FUNCTIONS=()

for func in `typeset -F | grep -Po '(?<=-f).*$' | sort`
do
	RH_FUNCTIONS+=($func);
done

# print help if nothing specified

if [ $# '<' '1' ]
then
	help
	exit 1
fi

# run command
for f in ${RH_FUNCTIONS[@]}
do
	if [ "$1" "=" "$f" ]
	then
		$f "${@:2}"
		exit $?
	fi
done

echo "Righthand function $1 not found, so now printing help..."
help
exit 1