#!/bin/bash

# helper script
# Used to wrap custom operations inside one script
############################# RH helper functions ##############################

ROOT=$(dirname $(readlink -f $0))

_rh_try_ret_help()
{
	if [ ! -z $RH_RUNTIME_REQUEST_HELP ]
	then
		echo $1
		exit 1;
	fi
}


##### In container functions #####

entrypoint()
{
    _rh_try_ret_help 'Run entrypoint logic inside controller container'

	disable_network_segmentation

	watch_container_changes &

    exec /bin/tail -f /dev/null
}

disable_network_segmentation()
{
		# disable network segmentation in docker
	if ! iptables-save | grep -q 'A FORWARD -j ACCEPT'
	then
		iptables -t filter -I FORWARD 1 -j ACCEPT
	fi

	if ! iptables-save | grep -q 'A PREROUTING -j ACCEPT'
	then
		iptables -t raw -I PREROUTING -j ACCEPT
	fi
}

update_container_routes()
{
	BF="(docker0"
	for br in $(docker network ls -q)
	do
		BF="${BF}|br-${br}"
	done
	BF="$BF)"
	if [ "$BF" = "()" ]; then BF="docker-empty-network-placeholder"; fi

	ACTUAL_ROUTES=$(route -n | grep -P "$BF" | grep -v '0\.0\.0\.0')

	DOCKER_ROUTES=$(docker ps -q | xargs -n 1 docker inspect --format '{{ if .Config.Labels.network_route }}{{ .Config.Labels.network_route }} {{range .NetworkSettings.Networks}} {{.IPAddress}}{{end}}{{end}}' | grep -vP '^$')

	# ADD ROUTES
    echo "$DOCKER_ROUTES" | while read -r req_route req_ip etc; do
        req_net="${req_route%%/*}"
        
        if ! echo "$ACTUAL_ROUTES" | grep -q "^$req_net"; then
			echo "Add route $req_route gw $req_ip"
            route add -net "$req_route" gw "$req_ip"
        fi
    done

	# DELETE ROUTES
	echo "$ACTUAL_ROUTES" | while read -r act_net act_gw act_mask etc; do
        if ! echo "$DOCKER_ROUTES" | grep -q "$act_net"; then
			echo "Delete route $act_net gw $act_gw"
            route del -net "$act_net" netmask $act_mask gw "$act_gw"
        fi
    done
}

watch_container_changes()
{
    update_container_routes
    docker events --filter 'event=start' --filter 'event=restart' --filter 'event=die' | while IFS= read -r line
    do
        # Start or die event
        if grep -qP '^[^ ]+ container (start|die)' <<< $line
        then
            update_container_routes
        fi
    done
}

############################ RH built-in functions #############################

help()
{
	_rh_try_ret_help "Returns RH help with the list of all annotated functions"

	echo "RH stands for 'right hand'. It is a wrapper script wherein you can collect tiny commands."
	echo "Specify one righthand function from the followings:"

	RH_RUNTIME_REQUEST_HELP=true

	for f in ${RH_FUNCTIONS[@]}
	do
		# if the command has help
		if type $f | grep -qzP '{\s+_rh_try_ret_help '
		then
			echo -e "\t$f - "$($f)
		fi
	done
}



############################## Application area ################################

# Collection available commands
RH_FUNCTIONS=()

for func in `typeset -F | grep -Po '(?<=-f).*$' | sort`
do
	RH_FUNCTIONS+=($func);
done

# print help if nothing specified

if [ $# '<' '1' ]
then
	help
	exit 1
fi

# run command
for f in ${RH_FUNCTIONS[@]}
do
	if [ "$1" "=" "$f" ]
	then
		$f "${@:2}"
		exit $?
	fi
done

echo "Righthand function $1 not found, so now printing help..."
help
exit 1